import { FAQ } from '@/services/faq';

// Build-time FAQ data - this would be populated during the build process
// In a real production setup, this could be generated by a build script
// that fetches from Firestore and writes to a JSON file

export const BUILD_TIME_FAQS: FAQ[] = [
  // This will be populated by the build process or can be manually updated
  // for now, we'll leave it empty and let the runtime fetching handle it
];

// Function to get FAQs with build-time fallback
export async function getBuildTimeFAQs(): Promise<FAQ[]> {
  // In production builds, return the pre-fetched data
  if (process.env.NODE_ENV === 'production' && BUILD_TIME_FAQS.length > 0) {
    return BUILD_TIME_FAQS;
  }

  // In development or if no build-time data, return empty array
  // The page will handle runtime fetching
  return [];
}

// Type for the build-time data structure
export interface BuildTimeData {
  faqs: FAQ[];
  lastUpdated: string;
}
