[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Optimize build performance and memory
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Clear webpack cache to prevent corruption
  NEXT_CLEAR_CACHE = "1"
  # Disable webpack cache in production to prevent corruption
  WEBPACK_CACHE = "false"
  # Optimize webpack for Netlify
  NEXT_WEBPACK_USE_POLLING = "1"
  # Reduce webpack memory usage
  WEBPACK_MEMORY_LIMIT = "2048"
  # Configure secrets scanning to allow public Firebase project ID and other public keys
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
  # Omit certain paths from secrets scanning to prevent false positives
  SECRETS_SCAN_OMIT_PATHS = ".firebaserc,.next/**,node_modules/**"

# Build cache configuration for faster builds
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Note: Cache clearing is handled in the build script instead of plugin

[dev]
  framework = "nextjs"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = ".next"

# Redirect rules for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Deployment hooks for page warming
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Post-deployment warmup
[context.production.environment]
  ENABLE_PAGE_WARMUP = "true"

[context.deploy-preview.environment]
  ENABLE_PAGE_WARMUP = "false" 