[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Optimize build performance and memory
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Clear webpack cache to prevent corruption
  NEXT_CLEAR_CACHE = "1"
  # Disable webpack cache in production to prevent corruption
  WEBPACK_CACHE = "false"
  # Optimize webpack for Netlify
  NEXT_WEBPACK_USE_POLLING = "1"
  # Reduce webpack memory usage
  WEBPACK_MEMORY_LIMIT = "2048"

# Build cache configuration for faster builds
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Clear cache before build to prevent webpack corruption
[[plugins]]
  package = "@netlify/plugin-cache-killer"

[dev]
  framework = "nextjs"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = ".next"

# Redirect rules for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Deployment hooks for page warming
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Post-deployment warmup
[context.production.environment]
  ENABLE_PAGE_WARMUP = "true"

[context.deploy-preview.environment]
  ENABLE_PAGE_WARMUP = "false" 